"""The objective of this notebook is to create a simple scikit-learn regression wrapper that will ease model training and benchmarking"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/05_classicml.regression.ipynb.

# %% auto 0
__all__ = ['SimpleRegressionModel']

# %% ../../nbs/05_classicml.regression.ipynb 3
import pandas as pd
from sklearn.linear_model import LinearRegression

# %% ../../nbs/05_classicml.regression.ipynb 4
class SimpleRegressionModel:
    def __init__(self):
        self.model = LinearRegression()
    
    def fit(self, X, y):
        self.model.fit(X, y)
        return self
    
    def predict(self, X):
        return self.model.predict(X)
    
    def predict_as_dataframe(self, X, degree, context_len):
        pred = self.predict(X)
        pred = pd.DataFrame(pred, index=X.index, columns=[f"t+{i+1}" for i in range(0, pred.shape[1])])
        pred.columns.name = "forecast_horizon"
        pred.index.name = "run_time"
        pred['degree'] = degree
        pred['context_len'] = context_len
        pred = pred.set_index(['degree', 'context_len'], append=True)
        pred = pred.reorder_levels(["degree", "context_len", "run_time"]).sort_index()
        return pred
