# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ombs_senegal',
                'doc_host': 'https://iraind.github.io',
                'git_url': 'https://github.com/iraind/ombs_senegal',
                'lib_path': 'ombs_senegal'},
  'syms': {'ombs_senegal.region': {'ombs_senegal.region.get_region_mask': ('region.html#get_region_mask', 'ombs_senegal/region.py')}}}
