# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ombs_senegal',
                'doc_host': 'https://iraind.github.io',
                'git_url': 'https://github.com/iraind/ombs_senegal',
                'lib_path': 'ombs_senegal'},
  'syms': {'ombs_senegal.core': {'ombs_senegal.core.foo': ('core.html#foo', 'ombs_senegal/core.py')}}}
