"""This module provides functionality for creating region masks from GeoDataFrames and xarray Datasets. It helps identify points that fall within specified geographic regions."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_region.ipynb.

# %% auto 0
__all__ = ['get_region_mask']

# %% ../nbs/02_region.ipynb 3
import xarray as xr
import geopandas as gpd
import regionmask

# %% ../nbs/02_region.ipynb 5
def get_region_mask(ds: xr.Dataset, gdf: gpd.GeoDataFrame) -> xr.DataArray:
    """Create a boolean mask from all geometries in the GeoDataFrame.
    Returns True for points within any geometry, False otherwise."""
    masked_region_with_nan = regionmask.mask_geopandas(gdf, ds)
    mask = ~xr.ufuncs.isnan(masked_region_with_nan)
    return mask
