"""T"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_tamsat.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/03_tamsat.ipynb 3
from pathlib import Path
import xarray as xr
import geopandas as gpd

from .region import get_region_mask
